# Random Sampling

In [12]:
import numpy as np


In [2]:
np.__version__

'1.26.4'

In [5]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [11]:
out=np.random.rand(3,2)
print(out)

[[0.64128552 0.95136517]
 [0.77230034 0.72965149]
 [0.06904552 0.35857956]]


Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [42]:
out1=np.random.rand(1000,1000)
out2

-0.00110028519551
0.999683483393


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [13]:
np.random.randint(0,4,(3,2))

array([[1, 1],
       [1, 3],
       [3, 1]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [15]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']
for items in range(10):
    print(np.random.choice(x,p=[0.3,0.5,0.2]))

b'5 out of 10'
b'5 out of 10'
b'5 out of 10'
b'2 out of 10'
b'5 out of 10'
b'5 out of 10'
b'3 out of 10'
b'5 out of 10'
b'2 out of 10'
b'2 out of 10'


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [25]:
out = np.random.choice(10,3)
print(out)

[6 6 7]


## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [27]:
out=np.arange(0,9)
print(out)
out1=np.random.permutation(out)
print(out1)

[0 1 2 3 4 5 6 7 8]
[3 4 8 0 6 2 5 1 7]


In [32]:
# Or we can use shuffle
out=np.arange(0,9)
print(out)
np.random.shuffle(out)
print(out)

[0 1 2 3 4 5 6 7 8]
[2 8 0 7 4 1 5 3 6]


## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [33]:
np.random.seed(10)